
server:
  port: 8091

spring:
  application:
    name: msvc-operador
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/operador_db
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka

